// <auto-generated />
using IoT.RPiController.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IoT.RPiController.Data.Migrations
{
    [DbContext(typeof(RPiContext))]
    partial class RPiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("IoT.RPiController.Data.Entities.ModuleConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Address")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte>("PortA")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("PortB")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ModuleConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
